/*
* @Author: sigou
* @Date:   2016-03-26 23:27:30
* @Last Modified by:   sigou
* @Last Modified time: 2016-04-11 14:13:41
*/


var FoodLists={
	"目录":[{
		"catagrogy":"类别1"
	},{
		"catagrogy":"类别2"
	},{
		"catagrogy":"类别3"
	},{
		"catagrogy":"类别4"
	},{
		"catagrogy":"类别5"
	},{
		"catagrogy":"类别6"
	},{
		"catagrogy":"类别7"
	},{
		"catagrogy":"类别8"
	},{
		"catagrogy":"类别9"
	},{
		"catagrogy":"类别10"
	}],
	"类别1":[{
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	},{
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	},{		
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	},{		
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	},{		
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	},{		
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	},{	
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	},{	
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	},{
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	},{	
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	},{	
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	}],
	"类别2":[{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	},

	{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	}],
	"类别3":[{	
		"imgSrc":"",
		"alt":"干煸四季豆菜品图",
		"foodName":"干煸四季豆",
		"foodName":"干煸四季豆",
		"foodPrice":"12",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"干煸四季豆菜品图",
		"foodName":"干煸四季豆",
		"foodName":"干煸四季豆",
		"foodPrice":"12",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"干煸四季豆菜品图",
		"foodName":"干煸四季豆",
		"foodName":"干煸四季豆",
		"foodPrice":"12",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"干煸四季豆菜品图",
		"foodName":"干煸四季豆",
		"foodName":"干煸四季豆",
		"foodPrice":"12",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"干煸四季豆菜品图",
		"foodName":"干煸四季豆",
		"foodName":"干煸四季豆",
		"foodPrice":"12",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"干煸四季豆菜品图",
		"foodName":"干煸四季豆",
		"foodName":"干煸四季豆",
		"foodPrice":"12",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"干煸四季豆菜品图",
		"foodName":"干煸四季豆",
		"foodName":"干煸四季豆",
		"foodPrice":"12",
		"foodUnit":"例"
	}],
	"类别4":[{	
		"imgSrc":"",
		"alt":"葱爆羊肉菜品图",
		"foodName":"葱爆羊肉",
		"foodName":"葱爆羊肉",
		"foodPrice":"12",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"葱爆羊肉菜品图",
		"foodName":"葱爆羊肉",
		"foodName":"葱爆羊肉",
		"foodPrice":"12",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"葱爆羊肉菜品图",
		"foodName":"葱爆羊肉",
		"foodName":"葱爆羊肉",
		"foodPrice":"12",
		"foodUnit":"例"
	},
	{	
		"imgSrc":"",
		"alt":"葱爆羊肉菜品图",
		"foodName":"葱爆羊肉",
		"foodName":"葱爆羊肉",
		"foodPrice":"12",
		"foodUnit":"例"
	}],
	"类别5":[{	
		"imgSrc":"",
		"alt":"干煸四季豆菜品图",
		"foodName":"干煸四季豆",
		"foodName":"干煸四季豆",
		"foodPrice":"12",
		"foodUnit":"例"
	}],
	"类别6":[{	
		"imgSrc":"",
		"alt":"葱爆羊肉菜品图",
		"foodName":"葱爆羊肉",
		"foodName":"葱爆羊肉",
		"foodPrice":"12",
		"foodUnit":"例"
	}],
  	"类别7":[{	
		"imgSrc":"",
		"alt":"回锅肉菜品图",
		"foodName":"回锅肉",
		"foodName":"回锅肉",
		"foodPrice":"29",
		"foodUnit":"例"
	}],
  	"类别8":[{
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	}],
  	"类别9":[{	
		"imgSrc":"",
		"alt":"葱爆羊肉菜品图",
		"foodName":"葱爆羊肉",
		"foodName":"葱爆羊肉",
		"foodPrice":"12",
		"foodUnit":"例"
	}],
  	"类别10":[{
		"imgSrc":"",
		"alt":"鱼香肉丝菜品图",
		"foodName":"鱼香肉丝",
		"foodName":"鱼香肉丝",
		"foodPrice":"18",
		"foodUnit":"例"
	}]
};
menuApp.controller('cataController',function($scope){
	$scope.catas=FoodLists["目录"];

	$scope._tab={
		index:0
	};
	$scope._foodLists={
		index:"类别1"
	};
	
	$scope.foodLists=FoodLists[$scope._foodLists.index];
	
	console.log(FoodLists[$scope._foodLists.index]);
	$scope.tabClick=function(e,index){
		$scope._tab.index=index;
		$scope._foodLists.index=e;
		$scope.foodLists=FoodLists[e];
	}
});